weatherApp/urls.py
from django.urls import path
from . import views

app_name = 'weatherApp'
urlpatterns = [
    path('', views.home, name="home"),
    path('delete/<city_name>/', views.city_delete, name="city_delete"),
]

weatherProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 


urlpatterns = [
    path('', include('weatherApp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weatherApp/models.py
from django.db import models

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

weatherApp/forms.py
from django.forms import ModelForm, TextInput
from .models import City


class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {'name': TextInput(attrs={'class': 'input', 'placeholder': 'City Name'})}

weatherApp/views.py
from django.shortcuts import redirect, render, get_object_or_404
import requests
from .models import City
from .forms import CityForm

# Create your views here.
def home(request):
    url = "http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=005f235fb8f211ddba4217fd7c8a6ede"
    errmsg = ''
    msgclass = ''
    msg = ''
    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            new_city = form.cleaned_data['name']
            city_count = City.objects.filter(name=new_city).count()
            if city_count == 0:
                r = requests.get(url.format(new_city)).json()
                if r['cod'] == 200:
                    form.save()
                    
                else:
                    errmsg = "The city is not exist in the world"
            else:
                errmsg = "Already city is added to database"
        if errmsg:
            msg = errmsg
            msgclass = 'is-danger'
        else:
            msg = "The city is successfully added in database"
            msgclass = 'is-success'
        
    form = CityForm()
   
    weather = []
    city = City.objects.all()
    for p in city:
        r = requests.get(url.format(p)).json()
        temparature_F= r['main']['temp']
        temparature_C = (temparature_F-32)*5/9
        city_weather={
            'city': p,
            'temparature': int(temparature_C),
            'description': r['weather'][0]['description'],
            'icon': r['weather'][0]['icon']
        }
        weather.append(city_weather)
    context={
        'weather': weather, 
        'form': form,
        'msg': msg,
        'msgclass': msgclass,
        }

    return render(request, 'weatherApp/index.html', context)

def city_delete(request, city_name):
    city = get_object_or_404(City, name= city_name)
    city.delete()

    return redirect('weatherApp:home')

weatherApp/templates/weatherApp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>WeatherApp|SajibUzzaman</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static '' %}img/sajib favicon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
      <!-- Google Fonts -->
      <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet"> 
      <!-- CSS
      ============================================ -->
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static '' %}css/bootstrap.min.css">
      <!-- Icon Font CSS -->
      <link rel="stylesheet" href="{% static '' %}css/font-awesome.min.css">
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
      
    
     
      
</head>

<body>

    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <div class='row'>
                      <!-- Header Social -->
                      <div class="header-social col-md-4 col-12">
                        <a href="http://www.facebook.com/sajibuzzaman98/"><i class="fa fa-facebook"></i></a>&nbsp &nbsp &nbsp
                        <a href="http://www.twitter.com/uzzamansajib/"><i class="fa fa-twitter"></i></a>&nbsp &nbsp &nbsp
                        <a href="http://www.linkedin.com/in/sajibuzzaman-bd/"><i class="fa fa-linkedin"></i></a>&nbsp &nbsp &nbsp
                        <a href="http://www.instagram.com/sajib_uzzaman/"><i class="fa fa-instagram"></i></a>&nbsp &nbsp &nbsp
                        <a href="http://www.youtube.com/sajibuzzaman/"><i class="fa fa-youtube"></i></a>
                    </div>

                    <!-- Header Logo -->
                    <h1 class="title">
                        What's the weather like?
                    </h1>
                </div>
                
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field has-addons">
                            <div class="control is-expanded">
                               {{form.name}}
                            </div>
                            <div class="control">
                                <button class="button is-info">
                                    Add City
                                </button>
                            </div>
                        </div>
                        
                        {% if msg %}
                            <div class="notification {{msgclass}}">
                                {{msg}}
                            </div>
                        {% endif %}
                            
                        
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    {% for a in weather %}


                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/{{a.icon}}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{a.city}}</span>
                                        <br>
                                        <span class="subtitle">{{a.temparature}}° C</span>
                                        <br> {{a.description}}
                                    </p>
                                </div>
                            </div>
                            <div class="media-right">
                                <a href="{%url 'weatherApp:city_delete' city_name=a.city%}">
                                 <button class='delete'></button>
                                </a>
                            </div>
                        </article>
                    </div>
                     {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>

    
</body>

</html> 